### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by JoshCunningHum** [JoshCunningHum/Dodong-webplayer#2]
I feel like the UI is a little bit "bland".

I would appreciate it if you can give at least a quick sketch for a new (elegant yet user-friendly) UI.

UI as of now:
![image](https://user-images.githubusercontent.com/40543984/151702739-2b91bf17-b83e-479c-af23-d55f144f61a5.png)

programmers would say: Can you please be more specific?

my answer: Just think of a way cooler looking UI okay?? but not too technical that it would like AutoCAD

**Comment by dotnize** [comment]
idk i made this in a paint-like program ehe

![2](https://user-images.githubusercontent.com/48910077/151735426-4f7f58e2-8621-4263-a100-05a26dce3d77.png)

You can probably just add the "previous" button but make it disabled/unclickable for now since that feature is currently broken

For the search and lyrics features, this can be done via the bot too but I think it's better if we just do this in the webplayer's node.js instance using `youtube-sr` (the bot uses this package for searching yt vids too) and some package for searching lyrics.

I would love to work on those 2 features above (or at least 1) myself if that's okay hehe, but it'll take some time cos idk much about express and http requests yet and I still have to familiarize myself with the project's structure

ps if the user inputs a URL we can just add the track to the discord bot directly instead of executing the search feature

**Comment by JoshCunningHum** [comment]
All icons, font, font size, and color are not final except the structure.
![webplayer sketch](https://user-images.githubusercontent.com/40543984/151788980-a3443490-29c6-4165-a7aa-7c3cb5675120.png)

Changes I want to make with the design
1. The search&lyrics is collapsable and is absolute (mean it can cover the queue list) to support multiple screen sizes
2. Hide the previous button (for now)
3. Create a progress indicator (the white part in the lower part) and might remove the progress bar


Technicalities
1. Play Results: The web player can't access the node js since it is still static (or should I say the node.js can't access the web player), so for now it will ask the bot for the info through WebSocket, BUT do not worry as I will implement this feature in the way that you intend to so that it would not overload the bot. I will only make a PR once I made the web player dynamic. The web player being static is only for the initial development (main features are still not finished). I looked into ``youtube-sr`` and it looks super convenient, with this I might be able to simulate correct audio visualizers without a data stream from the bot.

Some notes

1. Shuffle is a button and not a checkbox. see [here](https://github.com/Androz2091/discord-player/blob/6c46957f3fd93428dc0a58d122cd86d70aff8b63/src/Structures/Queue.ts#L455)
2. scrollable AND "reorder-able" (I am just making words now) by dragging songs in the queue list (user-friendly move function)
3. If User inputted a URL: yes I already implemented that
4. The login and settings page will cover the whole screen while assigning buttons to go back to the player (this deletes the player button in the menu)
5. The white portion below might be replaced with an audio visualizer if the progress bar is preserved.

**Comment by dotnize** [comment]
>1. Play Results: The web player can't access the node js since it is still static (or should I say the node.js can't access the web player)

It can, via http requests with fetch() and routing with express but I'm not sure if this is the most efficient way

This is how I did it with the vid I sent on discord


client sided script, in a button click event
```js
let response = await fetch('/search', {
    method: 'POST',
    cache: 'no-cache',
    headers: {
        'Content-Type': 'application/json'
    },
    referrerPolicy: 'no-referrer',
    body: JSON.stringify({ query: input }) // input is the string from the input/textbox element
});
let results = await response.json();
console.log(results); // will print the results array from the node.js response
// then do the magic to display "results" in the html stuff
 ```

node.js
```js
const YouTube = require("youtube-sr").default;
const bodyParser = require("body-parser"); // to parse the body contents from the POST request with fetch()

// use the express-static middleware to serve static pages (/public)
app.use(express.static("public"));

// body parser middleware
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.post('/search', function (req, res) {
    YouTube.search(req.body.query, { limit: 5, type: "video", safeSearch: true })
        .then(results => res.json(results))
        .catch(console.error);
});
```

**Comment by JoshCunningHum** [comment]
Oh this is new to me, I thought ``fetch`` is not available if run locally. Aight will try to implement this, I might don't even need to turn the web player dynamic with this
